"""`make demo` — drive the demo timeline so the presenter talks instead of clicking.

    python -m tools.demo [--base-url ...] [--no-kill] [--restore] [--dry-run]

Beats 1 through 6 run on the schedule in `data/seed/timeline.json`, which is generated by
`tools/gen_seed.py` and is the same file the seed fixtures come from. **Beat 7 (MCP) stays
manual** — it is the one worth pausing on, and a pause is a decision the presenter makes.

── Every expectation is CHECKED, and a mismatch is loud ────────────────────────────────

The timeline carries `expect`, `expect_rule`, `expect_risk_score` and
`expect_risk_score_non_null`. This runner asserts all four and prints a red MISMATCH line
when the system does something other than what the script says, then exits non-zero at the
end.

That is the point of running it before the demo rather than during. A runner that printed
the timeline's expectations instead of the system's answers would be a very expensive way to
read a JSON file — and it is exactly the failure mode `make eval` was built to avoid, one
screen over. Nothing here is hardcoded: every line printed is what the API returned.

── The rolling windows are reset first, and that is not tidiness ───────────────────────

A second run inside the observation TTL produces DIFFERENT results, and the first time this
runner was run twice in a row the warm-up beat and the drift beat swapped verdicts: the
warm-up scored 0.67 and stepped up, and the drift — arriving on top of a window that already
contained one — scored 0.08 and was allowed. Nothing was broken. The agent's history is
shared state, and the drift became the agent's normal.

That is the same defect class as F-040: an outcome that depends on ambient state, which does
not fail so much as wait for someone to run it at the wrong moment. On stage the wrong moment
is the second rehearsal.

So the demo agents' windows are cleared before the run, which makes each run start from the
same behavioural state and makes the timeline mean what it says. `--keep-windows` skips it,
for when the question is specifically what a warm agent looks like.

── A run SPENDS, and the preflight says so before it starts ────────────────────────────

The ledger is append-only and a demo run consumes real budget from the seeded mandates. It
does not reset, and it must not: a tool that credited budget back so its own script would
pass is a tool that has stopped testing the thing it claims to demonstrate.

After enough runs the cumulative cap is reached and beat 3.0 — an ordinary ₹475 purchase —
denies with `mandate.max_total`. Which is correct enforcement and a confusing demo, and it
is a confusing demo that appears on the eighth rehearsal rather than the first.

So the run is preflighted: what each mandate will spend against what it has left, refused up
front with the command to reset. The failure is legible instead of arriving as a wrong
verdict in the middle of a beat.

── Beat 6 is destructive, and reversible ───────────────────────────────────────────────

The tamper is a real superuser UPDATE against a committed record, because the control being
demonstrated is detection by cryptography and not prevention by the database. It therefore
leaves `make verify` reporting FAIL afterwards — permanently, which is correct and is also
a footgun on a laptop you have to demo from twice.

So the original value is written to `data/demo/last_tamper.json` and `--restore` puts it
back. Restoring is the same superuser UPDATE in reverse: we are undoing our own tamper by
exactly the means we made it, which is honest rather than a special case.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path
from typing import Any

import httpx
import psycopg
from redis.asyncio import Redis

from dwaar import clock
from dwaar.crypto import http_sig
from dwaar.crypto import keys as keymod
from dwaar.money import format_inr

REPO = Path(__file__).resolve().parents[1]
TIMELINE = REPO / "data" / "seed" / "timeline.json"
TAMPER_STATE = REPO / "data" / "demo" / "last_tamper.json"

SEED = 20260905
DEFAULT_BASE_URL = "http://127.0.0.1:8080"

BOLD, DIM, RESET = "\033[1m", "\033[2m", "\033[0m"
GREEN, RED, AMBER, CYAN = "\033[32m", "\033[31m", "\033[33m", "\033[36m"


def banner(beat: Any, title: str) -> None:
    print(f"\n{BOLD}{CYAN}{'━' * 78}{RESET}")
    print(f"{BOLD}  BEAT {beat}  ·  {title}{RESET}")
    print(f"{BOLD}{CYAN}{'━' * 78}{RESET}")


def note(text: str | None) -> None:
    if text:
        for line in _wrap(text, 74):
            print(f"  {DIM}{line}{RESET}")


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


class Runner:
    def __init__(self, base_url: str, *, allow_kill: bool, dry_run: bool) -> None:
        self.base_url = base_url.rstrip("/")
        self.allow_kill = allow_kill
        self.dry_run = dry_run
        self.mismatches: list[str] = []
        self.last_request: dict[str, Any] | None = None

    # ── transport ───────────────────────────────────────────────────────────────

    def _sign(self, agent_id: str, body: bytes) -> dict[str, str]:
        key = keymod.derive_private_key(SEED, "agent", agent_id)
        return http_sig.sign_request(
            key, method="POST", path="/v1/authorize", body=body, keyid=agent_id,
            created=clock.unix(), nonce=uuid.uuid4().hex,
        )

    async def authorize(self, client: httpx.AsyncClient, beat: dict) -> dict[str, Any]:
        payload = {
            "agent_id": beat["agent"],
            "mandate_id": beat["mandate"],
            "action": beat.get("action", "purchase"),
            "amount_paise": beat["amount_paise"],
            "idempotency_key": f"demo-{uuid.uuid4().hex[:20]}",
        }
        # `instrument_bin` and `cart_id` are behavioural context, hashed before they are
        # stored and never present in the record raw. Omitting them is what F-045 was.
        for optional in ("category", "sku", "free_text", "instrument_bin", "cart_id"):
            if beat.get(optional) is not None:
                payload[optional] = beat[optional]

        body = json.dumps(payload, separators=(",", ":")).encode()
        headers = self._sign(beat["agent"], body)
        headers["Content-Type"] = "application/json"
        response = await client.post(
            f"{self.base_url}/v1/authorize", content=body, headers=headers
        )
        self.last_request = beat
        result = {"status_code": response.status_code, **_json(response)}

        # ── rule_fired and risk_score come from the RECORD, not the response ────────
        #
        # `/v1/authorize` deliberately does not return `rule_fired`. Outbound reason codes
        # are coarse and inbound ones are fine-grained (threat 10): telling an agent exactly
        # which limit it hit lets it binary-search the mandate. The first version of this
        # runner read `rule_fired` off the response and reported None for every beat,
        # because it is not there and should not be.
        #
        # So the assertions read the chained record, which is the artifact the demo is about
        # anyway — and reading it proves the record exists, which the response alone does
        # not.
        record_id = result.get("decision_id")
        if record_id:
            detail = await client.get(f"{self.base_url}/v1/console/decisions/{record_id}")
            result["record"] = _json(detail)
        return result

    # ── beats ───────────────────────────────────────────────────────────────────

    async def request_beat(self, client: httpx.AsyncClient, beat: dict) -> None:
        banner(beat["beat"], f"{beat.get('action', 'purchase')} {format_inr(beat['amount_paise'])}")
        note(beat.get("note"))

        # `_burst_index` means this event only makes sense after a run-up: the drift beat is
        # "10x ticket, 20x velocity, same SKU repeated", and velocity is a rolling window, so
        # a cold agent has none. The warm-up requests are the PREVIOUS beat repeated — the
        # timeline's own words for what normal looks like for this agent.
        burst = beat.get("_burst_index")
        if burst and self.last_request is not None:
            warm = dict(self.last_request)
            print(f"  {DIM}run-up: {burst} requests at this agent's established rate{RESET}")
            for _ in range(int(burst)):
                await self.authorize(client, warm)

        result = await self.authorize(client, beat)
        self.report(beat, result)

    def report(self, beat: dict, result: dict) -> None:
        record = result.get("record") or {}
        decision = result.get("decision", f"HTTP {result['status_code']}")
        rule = record.get("rule_fired")
        # A tristate on purpose. `MISSING` means we could not read the record at all, which
        # is a different failure from a record whose score is NULL — and NULL is the claim
        # beat 2 rests on entirely.
        risk = record.get("risk_score", "MISSING") if record else "MISSING"
        print(
            f"  → {BOLD}{decision.upper():<8}{RESET} "
            f"reason={result.get('reason_code', '?'):<18} rule={rule or '—':<26} "
            f"seq={result.get('chain_seq', '?')} {result.get('latency_us', '?')}µs"
        )
        if result.get("bounded_amount_paise"):
            print(f"    bound to {format_inr(result['bounded_amount_paise'])}")

        expected = beat.get("expect")
        if expected and decision != expected:
            self.fail(beat, f"expected {expected!r}, got {decision!r}")
        if beat.get("expect_rule") and rule != beat["expect_rule"]:
            self.fail(beat, f"expected rule {beat['expect_rule']!r}, got {rule!r}")

        # The two mirrored assertions. Beat 2 denies with a NULL score because the gate
        # settled it; beat 3.1 denies with a non-null one because only the model could have.
        # Together they are the demo's clearest thirty seconds, and each is worthless
        # without the other.
        if "expect_risk_score" in beat and beat["expect_risk_score"] is None:
            if risk == "MISSING":
                self.fail(beat, "could not read the record, so NULL cannot be asserted")
            elif risk is not None:
                self.fail(beat, f"risk_score must be NULL and is {risk!r}")
            else:
                stages = record.get("stages_executed") or []
                print(f"    {GREEN}risk_score = NULL — the model was never consulted{RESET}")
                # The corroborating half. A NULL alone could mean the scorer failed; the
                # ABSENCE of the scoring stage is what makes it mean "short-circuited".
                if "score_risk" in stages:
                    self.fail(beat, "score_risk ran; a NULL here would be a failure, not a gate")
                else:
                    print(f"    {DIM}stages: {', '.join(stages)}{RESET}")
        if beat.get("expect_risk_score_non_null"):
            if risk in (None, "MISSING"):
                self.fail(
                    beat, "risk_score must be non-null; only the model could have caught this"
                )
            else:
                print(f"    {GREEN}risk_score = {risk} — the model earned its place here{RESET}")

    def fail(self, beat: dict, message: str) -> None:
        text = f"beat {beat['beat']}: {message}"
        self.mismatches.append(text)
        print(f"  {RED}{BOLD}MISMATCH{RESET} {RED}{message}{RESET}")

    def kill_beat(self, beat: dict) -> None:
        target = beat["target"]
        banner(beat["beat"], f"kill {target}")
        note(beat.get("note") or f"expect: {beat['expect']}")

        if not self.allow_kill:
            print(f"  {AMBER}--no-kill: not touching {target}{RESET}")
            return
        if shutil.which("docker") is None or self.dry_run:
            # Docker is not required for the rest of the demo, so an absent runtime is an
            # instruction rather than a failure. F-010 tracks the container path.
            print(f"  {AMBER}docker unavailable — run this yourself:{RESET}")
            print(f"    {BOLD}docker kill {target}{RESET}")
            return
        outcome = subprocess.run(  # noqa: S603
            ["docker", "kill", target], capture_output=True, text=True, check=False
        )
        if outcome.returncode == 0:
            print(f"  {GREEN}killed {target}{RESET}")
        else:
            print(f"  {AMBER}could not kill {target}: {outcome.stderr.strip()}{RESET}")

    def tamper_beat(self, beat: dict, dsn: str) -> None:
        banner(beat["beat"], "tamper the audit trail")
        note(beat.get("note"))
        if self.dry_run:
            print(f"  {AMBER}--dry-run: not tampering{RESET}")
            return
        tamper(dsn)
        print()
        verify_and_print(dsn)


def tamper(dsn: str, merchant: str = "mch_demo0001") -> None:
    """The superuser UPDATE. It MUST succeed — that is the precondition, not the finding.

    ── Which row, and why it matters ───────────────────────────────────────────────────

    The newest permitting record with an amount: the one this demo run just wrote.

    Not an arbitrary old one, and that is not cosmetic. `decision_records` carries NOT VALID
    CHECK constraints — migration 0014's `injection_flag` tristate is one — and a NOT VALID
    constraint still governs UPDATE. So touching a row written before a constraint existed
    re-checks it against that constraint and the UPDATE is REFUSED.

    The first version of this function picked `seq 3` and was refused by exactly that:
    a record written before the injection detector existed, carrying `injection_flag=false`
    with no `detect_injection` stage. The tamper failed, which would have been demo beat 6
    failing on stage for a reason nobody in the room could follow.

    Migration 0007 states the rule this violates — "a superuser MUST be able to tamper,
    because the control being demonstrated is detection by cryptography, not prevention by
    DBMS" — and it is worth recording that a NOT VALID CHECK on this table quietly erodes it.
    Migration 0017 uses a BEFORE INSERT trigger for that reason. 0014's constraint predates
    the observation; picking a current row is the fix here, and FAILURES.md carries the
    general form.
    """
    candidates = "".join(
        [
            "SELECT record_id, seq, amount_paise FROM decision_records ",
            "WHERE merchant_id = %s AND amount_paise IS NOT NULL AND amount_paise <> 500000 ",
            "AND decision IN ('allow','bound') ORDER BY seq DESC LIMIT 10",
        ]
    )
    with psycopg.connect(dsn) as conn:
        rows = conn.execute(candidates, (merchant,)).fetchall()
        if not rows:
            print(f"  {AMBER}no record to tamper — run the request beats first{RESET}")
            return

        record_id = seq = original = None
        for record_id, seq, original in rows:  # noqa: B007 — used after the loop
            try:
                with conn.transaction():
                    conn.execute(
                        "UPDATE decision_records SET amount_paise = 500000 "
                        "WHERE record_id = %s",
                        (record_id,),
                    )
                break
            except psycopg.errors.CheckViolation as exc:
                # A row written before a constraint existed. Say which and move on rather
                # than failing the beat — see the docstring.
                name = _constraint(exc)
                print(f"  {DIM}seq {seq} is governed by {name}; trying an older one{RESET}")
        else:
            print(f"  {RED}every candidate row was refused by a constraint{RESET}")
            return
        conn.commit()

    TAMPER_STATE.parent.mkdir(parents=True, exist_ok=True)
    TAMPER_STATE.write_text(
        json.dumps({"record_id": str(record_id), "seq": seq, "amount_paise": original}),
        encoding="utf-8",
    )
    print(f"  {BOLD}UPDATE decision_records SET amount_paise = 500000 WHERE seq = {seq};{RESET}")
    print(f"  {GREEN}UPDATE 1{RESET}  — the tamper SUCCEEDED, as it must")
    where = TAMPER_STATE.relative_to(REPO)
    print(f"  {DIM}original amount {format_inr(original)} saved to {where}{RESET}")


def _constraint(exc: Exception) -> str:
    text = str(exc)
    marker = 'check constraint "'
    if marker in text:
        return text.split(marker, 1)[1].split('"', 1)[0]
    return type(exc).__name__


def restore(dsn: str) -> int:
    """Undo the tamper, by exactly the means it was made."""
    if not TAMPER_STATE.exists():
        print("no recorded tamper to restore")
        return 0
    state = json.loads(TAMPER_STATE.read_text())
    with psycopg.connect(dsn) as conn:
        conn.execute(
            "UPDATE decision_records SET amount_paise = %s WHERE record_id = %s",
            (state["amount_paise"], state["record_id"]),
        )
        conn.commit()
    TAMPER_STATE.unlink()
    print(f"restored seq {state['seq']} to {format_inr(state['amount_paise'])}")
    return 0


def verify_and_print(dsn: str) -> bool:
    from dwaar.verify_cli import _render, verify

    findings = verify(dsn, merchant="mch_demo0001")
    print(_render(findings))
    return findings.ok


def _json(response) -> dict:
    try:
        return response.json()
    except Exception:  # noqa: BLE001
        return {"reason_code": "unparseable"}


async def reset_windows(redis_url: str, timeline: list[dict], dsn: str) -> int:
    """Clear the demo agents' rolling behavioural windows.

    Scoped to the agents named in the timeline — never `FLUSHDB`, which would take the nonce
    store with it and turn a reproducibility measure into a replay-defence outage.

    The window is keyed on `(agent_id, principal_id)` and the timeline knows only the agent,
    so the principal comes from the mandate. That join is the reason this is not a one-liner.
    """
    from dwaar.risk.observations import OBS_PREFIX, PAY_PREFIX

    agents = {b["agent"]: b["mandate"] for b in timeline if b.get("agent")}
    if not agents:
        return 0

    with psycopg.connect(dsn) as conn:
        pairs = conn.execute(
            "SELECT agent_id, principal_id FROM mandates WHERE mandate_id = ANY(%s)",
            (list(agents.values()),),
        ).fetchall()

    redis = Redis.from_url(redis_url)
    try:
        keys = [
            f"{prefix}:{agent_id}:{principal_id}"
            for agent_id, principal_id in pairs
            for prefix in (OBS_PREFIX, PAY_PREFIX)
        ]
        return int(await redis.delete(*keys)) if keys else 0
    finally:
        await redis.aclose()


def preflight_budget(timeline: list[dict], dsn: str) -> list[str]:
    """What each mandate will spend against what it has left. Returns complaints.

    Only PERMITTING beats spend — a beat the timeline expects to be denied consumes nothing,
    and counting it would refuse to start a run that would have been fine. The run-up
    requests behind `_burst_index` are counted, because they are real requests that really
    reserve.
    """
    needed: dict[str, int] = {}
    for beat in timeline:
        if beat.get("control") or beat.get("expect") == "deny":
            continue
        multiplier = 1 + int(beat.get("_burst_index") or 0)
        needed[beat["mandate"]] = (
            needed.get(beat["mandate"], 0) + beat["amount_paise"] * multiplier
        )
    if not needed:
        return []

    with psycopg.connect(dsn) as conn:
        balances = dict(
            conn.execute(
                "SELECT mandate_id, (array_agg(balance_after ORDER BY entry_id DESC))[1] "
                "FROM budget_ledger WHERE mandate_id = ANY(%s) GROUP BY mandate_id",
                (list(needed),),
            ).fetchall()
        )

    complaints = []
    for mandate_id, amount in sorted(needed.items()):
        remaining = balances.get(mandate_id)
        if remaining is None:
            complaints.append(f"{mandate_id} has no ledger — the seed was never loaded")
        elif remaining < amount:
            complaints.append(
                f"{mandate_id} needs {format_inr(amount)} and has {format_inr(remaining)}"
            )
    return complaints


async def run(args) -> int:
    timeline = sorted(json.loads(TIMELINE.read_text()), key=lambda b: b["t"])
    runner = Runner(args.base_url, allow_kill=not args.no_kill, dry_run=args.dry_run)

    print(f"{BOLD}DWAAR — demo timeline{RESET}")
    print(f"{DIM}{len(timeline)} beats over {timeline[-1]['t']}s. Beat 7 (MCP) is manual.{RESET}")

    async with httpx.AsyncClient(timeout=15.0) as client:
        try:
            health = (await client.get(f"{args.base_url}/health")).json()
        except Exception as exc:  # noqa: BLE001
            print(f"{RED}the API is not reachable at {args.base_url}: {type(exc).__name__}{RESET}")
            print("start it with `make up`, or `uvicorn dwaar.api.app:app --port 8080`")
            return 2
        # Preflight. A postgres that is down produces a 500 per beat and a wall of
        # mismatches that all have one cause — which is a worse report than one line saying
        # so. `.env` carries Docker hostnames; from the host they do not resolve.
        down = [
            name
            for name, component in health.get("components", {}).items()
            if component["status"] == "down" and component["severity"] == "critical"
        ]
        if down:
            print(f"{RED}the gateway reports {', '.join(down)} DOWN — every beat would 500{RESET}")
            for name in down:
                print(f"  {DIM}{name}: {health['components'][name]['reason']}{RESET}")
            print(f"  {DIM}DATABASE_URL_APP is probably pointing at a Docker hostname.{RESET}")
            return 2

        # The ledger is append-only and a run spends from it. Checked BEFORE the first
        # beat so an exhausted mandate is a sentence rather than a surprise deny in beat 3.
        complaints = preflight_budget(timeline, args.superuser_dsn)
        if complaints and not args.ignore_budget:
            print(f"{RED}the seeded mandates cannot fund this run:{RESET}")
            for line in complaints:
                print(f"  {line}")
            print()
            print(f"  {DIM}A demo run consumes real budget and the ledger does not reset —")
            print("  crediting it back so the script passes would mean the demo had stopped")
            print(f"  demonstrating enforcement. Reset the data instead:{RESET}")
            reset = "make clean && make up && make seed && python -m scripts.seed_db"
            print(f"    {BOLD}{reset}{RESET}")
            print(f"  {DIM}or run with --ignore-budget to watch the cap actually bite.{RESET}")
            return 2

        if not args.keep_windows:
            try:
                cleared = await reset_windows(args.redis_url, timeline, args.superuser_dsn)
                print(f"{DIM}cleared {cleared} rolling window(s) — see the module docstring{RESET}")
            except Exception as exc:  # noqa: BLE001
                print(f"{AMBER}could not clear the windows ({type(exc).__name__}); a second "
                      f"run in the same TTL will not reproduce the first{RESET}")

        simulated = [n for n, i in (health.get("integrations") or {}).items() if i["simulated"]]
        if simulated:
            names = ", ".join(simulated)
            print(f"{AMBER}SIMULATED: {names}{RESET}  {DIM}(say this out loud){RESET}")

        started = time.perf_counter()
        for beat in timeline:
            # The timeline's own clock. `perf_counter` because this is an elapsed duration
            # and a wall clock that steps would desynchronise the whole run.
            delay = beat["t"] - (time.perf_counter() - started)
            if delay > 0 and not args.fast:
                await asyncio.sleep(delay)

            control = beat.get("control")
            if control == "kill_container":
                runner.kill_beat(beat)
            elif control == "tamper":
                runner.tamper_beat(beat, args.superuser_dsn)
            else:
                await runner.request_beat(client, beat)

    print(f"\n{BOLD}{CYAN}{'━' * 78}{RESET}")
    if runner.mismatches:
        print(f"{RED}{BOLD}  {len(runner.mismatches)} beat(s) did not match the script:{RESET}")
        for line in runner.mismatches:
            print(f"    {RED}{line}{RESET}")
        print(f"\n  {DIM}Reported, not smoothed over. What the system did is the result.{RESET}")
        return 1
    print(f"{GREEN}{BOLD}  every beat matched the script{RESET}")
    print(f"  {DIM}Beat 7 (MCP) is manual: see dwaar/mcp/README.md{RESET}")
    if TAMPER_STATE.exists():
        print(f"  {AMBER}the chain is tampered. `make demo-restore` puts it back.{RESET}")
    return 0


def main(argv: list[str] | None = None) -> int:
    from dwaar.config import get_settings

    settings = get_settings()
    parser = argparse.ArgumentParser(prog="dwaar-demo", description=__doc__.splitlines()[0])
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--superuser-dsn", default=settings.database_url_superuser)
    parser.add_argument("--redis-url", default=settings.redis_url)
    parser.add_argument(
        "--keep-windows",
        action="store_true",
        help="do not clear the agents' rolling windows first (a second run then differs)",
    )
    parser.add_argument(
        "--ignore-budget",
        action="store_true",
        help="run even if a mandate cannot fund it — the cumulative cap then bites",
    )
    parser.add_argument("--no-kill", action="store_true", help="skip the container beats")
    parser.add_argument("--fast", action="store_true", help="ignore the schedule; run flat out")
    parser.add_argument("--dry-run", action="store_true", help="no kills, no tamper")
    parser.add_argument("--restore", action="store_true", help="undo beat 6's tamper and exit")
    args = parser.parse_args(argv)

    if args.restore:
        return restore(args.superuser_dsn)
    return asyncio.run(run(args))


if __name__ == "__main__":
    sys.exit(main())
