"""`python -m tools.lock_inputs` — record what the held-out run is a test OF.

── Why this is not bookkeeping ─────────────────────────────────────────────────────────

A held-out result is only evidence if the thing being tested was fixed before the test. If
the model, the thresholds, the feature code or the policy moved after the agents ran, the
number that comes out measures nothing — and a reader has no way to tell from the outside.
The hashes are what let them tell.

It matters more here than it usually would, because of F-044: an expectation in this
repository was already once edited to match a measurement, with a good paragraph attached,
and the paragraph was fine while the measurement was not. The defence against that is not
better judgement afterwards. It is a record made beforehand.

── Everything here is computed ─────────────────────────────────────────────────────────

Rule 4 of the project: no hardcoded metrics, every number computed at run time. That applies
to this file above all, since its entire purpose is to be believed. The seeds are read out of
the Makefile rather than restated, the model version out of the bundle, the policy version
out of the database, and the hashes off disk.

── The SHA is the PARENT of the lock commit ────────────────────────────────────────────

Unavoidably: recording a commit hash inside a file and then committing that file changes the
hash. So `main at lock time` is the commit containing the inputs, and this file lands on top
of it. Both are stated rather than one being quietly approximate.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "eval" / "LOCKED_INPUTS.md"

#: Files a `risk_score` is a function of. Hashed individually rather than as a tarball, so a
#: reader can check the one they care about without reproducing our archive format.
MODEL_SUFFIXES = (".onnx", ".json")


def sh(*args: str) -> str:
    return subprocess.run(  # noqa: S603
        args, cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.strip()


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def makefile_var(name: str) -> str:
    """Read a seed out of the Makefile rather than restating it here.

    Restating it would make this file a second source of truth for a number whose entire
    value is that there is one — and the two would drift on the first run someone did with
    an override.
    """
    text = (REPO / "Makefile").read_text(encoding="utf-8")
    match = re.search(rf"^{name}\s*\?=\s*(\S+)", text, re.M)
    return match.group(1) if match else "unset"


def database_facts(dsn: str) -> dict[str, object]:
    import psycopg

    try:
        with psycopg.connect(dsn, connect_timeout=3) as conn:
            approved, version = conn.execute(
                "SELECT count(*), coalesce(max(version), 0) FROM policies "
                "WHERE approved_by IS NOT NULL"
            ).fetchone()
            schema = conn.execute("SELECT max(version) FROM schema_migrations").fetchone()[0]
            records = conn.execute("SELECT count(*) FROM decision_records").fetchone()[0]
        return {
            "approved_policies": approved,
            "policy_version": version,
            "schema": schema,
            "records": records,
        }
    except Exception as exc:  # noqa: BLE001
        # Reported, never defaulted. A lock file that silently substituted zeros would be
        # worse than one that says the database was unreachable.
        return {"error": f"{type(exc).__name__}: {exc}"}


def render(dsn: str) -> str:
    bundle = json.loads((REPO / "models/risk/bundle.json").read_text(encoding="utf-8"))
    injection = json.loads((REPO / "models/injection/weights.json").read_text(encoding="utf-8"))
    facts = database_facts(dsn)
    artifacts = sorted(
        p for p in (REPO / "models").rglob("*") if p.is_file() and p.suffix in MODEL_SUFFIXES
    )
    dirty = bool(sh("git", "status", "--porcelain"))
    main_sha = sh("git", "rev-parse", "HEAD")
    held_out_sha = sh("git", "rev-parse", "held-out")

    lines = [
        "# Locked inputs — the held-out run",
        "",
        "**Recorded before the held-out agents were run. Nothing below changed afterwards.**",
        "",
        "A held-out result is only evidence if the thing being tested was fixed before the",
        "test. If the model, the thresholds, the feature code or the policy moved after the",
        "agents ran, the number that comes out measures nothing, and a reader has no way to",
        "tell from the outside. The hashes are what let them tell.",
        "",
        "Generated by `python -m tools.lock_inputs`. Every figure is read from the artifact,",
        "the Makefile or the database — none is typed into this file.",
        "",
        "## Code",
        "",
        "| | |",
        "|---|---|",
        f"| `main`, the commit holding these inputs | `{main_sha}` |",
        f"| `held-out`, committed unread by this session | `{held_out_sha}` |",
        f"| uncommitted changes present at generation | `{'yes' if dirty else 'no'}` |",
        f"| schema migration | `{facts.get('schema', '?')}` |",
        "",
        "Recording a hash inside a file and then committing that file changes the hash, so",
        "`main` above is the commit containing the inputs and this file lands on top of it.",
        "",
        "## Model",
        "",
        "| | |",
        "|---|---|",
        f"| risk model version | `{bundle['model_version']}` |",
        f"| features | {len(bundle['feature_names'])}, ordered as `dwaar/risk/features.py` |",
        f"| injection model version | `{injection.get('model_version', 'n/a')}` |",
        f"| step-up band | `{bundle.get('step_up_band', 'see dwaar/risk/bands.py')}` |",
        f"| deny band | `{bundle.get('deny_band', 'see dwaar/risk/bands.py')}` |",
        "",
        "A stored row replayed against this bundle reproduces its `risk_score` exactly. That",
        "is what makes the score evidence rather than an assertion, and it is why the bundle",
        "is hashed rather than merely named.",
        "",
        "```",
    ]
    lines += [f"{digest(path)}  {path.relative_to(REPO)}" for path in artifacts]
    lines += [
        "```",
        "",
        "## Data and seeds",
        "",
        "| | |",
        "|---|---|",
        f"| `TRAFFIC_SEED` — training traffic | `{makefile_var('TRAFFIC_SEED')}` |",
        f"| `EVAL_SEED` — measurement traffic | `{makefile_var('EVAL_SEED')}` |",
        f"| approved policies | {facts.get('approved_policies', '?')} "
        f"(max version {facts.get('policy_version', '?')}) |",
        f"| `decision_records` at lock time | {facts.get('records', '?'):,} |"
        if isinstance(facts.get("records"), int)
        else f"| `decision_records` at lock time | {facts.get('error', '?')} |",
        "",
        "The two seeds are different on purpose: the agents the model is measured on are not",
        "the agents it was trained on. Same seed would have meant reporting performance on",
        "identities whose entire request stream the model had already learned.",
        "",
        "## What this pins, and what it does not",
        "",
        "**Pinned:** the two ONNX graphs, the feature ordering they were fitted against, the",
        "calibration breakpoints, the injection weights, the approved policy set, and the",
        "commit containing the code that computes the vector.",
        "",
        "**Not pinned: the traffic.** The held-out agents are seeded and their request streams",
        "are reproducible, but the rolling windows they accumulate are wall-clock dependent, so",
        "a re-run produces similar rather than identical numbers. That is a property of the",
        "measurement and it is stated rather than hidden — F-044 is what happens when it is",
        "not, and the mitigation there was to clear the windows so two runs agree.",
        "",
        "**Also not pinned, and worth saying plainly: the held-out agents were isolated, not",
        "independently authored.** This is a solo build. `zoo/HELD_OUT_SPEC.md` was the whole",
        "input to a separate session with no access to `dwaar/risk/`, no sight of the feature",
        "list and no thresholds; that session's work was committed by this one without being",
        "read. It is a weaker guarantee than a second author and it is the honest one.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    import argparse

    from dwaar.config import get_settings

    parser = argparse.ArgumentParser(prog="lock-inputs", description=__doc__.splitlines()[0])
    parser.add_argument("--dsn", default=None, help="defaults to DATABASE_URL_APP")
    parser.add_argument("--print", action="store_true", help="stdout instead of the file")
    args = parser.parse_args(argv)

    text = render(args.dsn or get_settings().database_url_app)
    if args.print:
        print(text)
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
